#!/usr/bin/env python


if "LIB_CUDA" in bld.env:
    bld.program(source="nvme2gpu_read.c",
                target="nvme2gpu_read",
                use="donard ARGCONFIG")

    bld.program(source="nvme2gpu_write.c",
                target="nvme2gpu_write",
                use="donard ARGCONFIG")

bld.program(source="nvme2map_read.c",
            target="nvme2map_read",
            use="donard ARGCONFIG")

bld.program(source="nvme2map_write.c",
            target="nvme2map_write",
            use="donard ARGCONFIG")
